# General Sessions
<span style="color: #FF7733;">**CHANGE ME**</span> 
General Sessions will be held on Sunday, September 4, 2022, 4-7 pm (NPT) and Saturday, September 10, 2022, 4-7 pm (NPT).

## Before the General Session {-}

* **Everyone: Please fill out your [introductory form](https://forms.gle/Bf1aUH8fD6F78gvG9){target="_blank"}.** This is to gauge participants' interests and the workshops' effectiveness. This form is anonymous, but critical to our ability to offer courses in the future. Thank you.

* **Everyone: Please fill out your [video & photo waiver](https://forms.gle/k6CVMT9EJHC2hqBc9){target="_blank"}.** The workshops will be recorded to help with future learning. Some stills from the sessions may be used for future marketing. Please fill this out even if you already answered the question on the anonymous introductory form. We need a waiver tied to your name.

* **Everyone: Ensure you are able to log onto Zoom.** Your calendar hold with the Zoom link will be in your inbox shortly.

* <span style="color: #FF7733;">**Technical sessions ONLY**</span>**: Sign up for [Google Earth Engine](https://earthengine.google.com/signup/){target="_blank"}.** Please do this as soon as possible! Sometimes it takes longer than expected to go through. Signing up for Google Earth Engine is free and **requires a Google account**. Instructions can be found in the [Google Earth Engine Section](https://woodwellrisk.github.io/Nepal_Workshops/google-earth-engine.html) of this website. Consider creating it "For myself", if you don't already have an account. 

* **For those not comfortable in English: Consider downloading the General Session slideshow .pdf (coming soon).** The speaker's notes are written out in English as a form of subtitles. There will also be Nepali speakers on the call who can translate.

## Planned Modules {-}

A .pdf of planned modules can be found [here](https://github.com/WoodwellRisk/Nepal_Workshops/blob/master/course_materials/Workshop_Invitation.pdf){target="_blank"}.

*Participants will be polled on preferences for Modules 3a-c.

**Module 1**  Introduction (Bishal Bhardwaj)

**Module 2**  Climate Change Risk and Mountain Development (Prof. Rajesh K Rai, Ph.D.)

**Module 3a***  Components of Risk & Reading Maps (Darcy Glenn)

* Discuss the three components of risk:

  +	Hazard

  +	Vulnerability

  +	Capacity

* Look at maps that show the three components of risk

  +	Identify components

  +	Discuss what is important and relevant on the maps

**Module 3b***  Introduce What Climate Models Can and Cannot Do (Darcy Glenn)

* Importance of Ensembles

* Temporal Resolutions

  +	If time frames are too short, the results will not be accurate.
  
  +	Best practice is to look at data over a 30 year time frame.

* Spatial Resolutions

  +	Complex landscapes are better modeled with high resolution.

  +	Mountains are more difficult  to model than flat plains.

* Very good at rates of change

  +	Overview of basic modeling methodology - conceptual

**Module 3c*** Risk and Social Communication (Speaker To Be Decided)

**Module 4**  Recap and Q&A (Bishal Bharadwaj, Prof. Rajesh K Rai, Darcy Glenn)

## Powerpoints {-}
PDF files of the Powerpoints can be found [here](https://github.com/WoodwellRisk/Nepal_Workshops/upload/master/course_materials).

## Videos {-}
[**General Session - Cohort A - Sunday, September 4, 2022**](https://woodwellclimate-org.zoom.us/rec/share/qiLKS2EuP2XmvDP90gJnIo7fJNb6-hQ3oJR03mnJWmo6PpBkYRlXlCRCnf3U9mDN.whzo-e76i_WsBrzE)

[**General Session - Cohort B - Saturday, September 10, 2022**](https://woodwellclimate-org.zoom.us/rec/share/xUGqan9410HSc3dJXtBLsVYdghOtzARIXBcdLFIWhZ8xh57p7Lzze9AymC8LRZJJ._HeluELmjog99tBj)

